# Generated by Django 4.2.7 on 2025-09-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_numero_documento_paciente_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='prioridad',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('nivel_1', 'Nivel 1: Prioridad muy alta'), ('nivel_2', 'Nivel 2: Prioridad alta'), ('nivel_3', 'Nivel 3: Prioridad media'), ('nivel_4', 'Nivel 4: Prioridad baja'), ('nivel_5', 'Nivel 4: Prioridad muy baja')], default='pendiente', max_length=20),
        ),
    ]
